export const usuarios = [
  {
    idUsuario: 1,
    nomeCliente: "João da Silva",
    valor: 1000,
    dataVencimento: "2023-10-15",
    status: "Pendente",
    descricao: "Pagamento do serviço de consultoria",
  },
  {
    idUsuario: 2,
    nomeCliente: "Maria Santos",
    valor: 750,
    dataVencimento: "2023-09-30",
    status: "Pago",
    descricao: "Aluguel do apartamento",
  },
  {
    idUsuario: 3,
    nomeCliente: "Pedro Oliveira",
    valor: 500,
    dataVencimento: "2023-10-05",
    status: "Pendente",
    descricao: "Compra de material de escritório",
  },
  {
    idUsuario: 4,
    nomeCliente: "Ana Pereira",
    valor: 300,
    dataVencimento: "2023-09-25",
    status: "Pago",
    descricao: "Manutenção do carro",
  },
  {
    idUsuario: 5,
    nomeCliente: "Lucas Fernandes",
    valor: 1200,
    dataVencimento: "2023-10-10",
    status: "Pendente",
    descricao: "Pagamento de aluguel",
  },
  {
    idUsuario: 6,
    nomeCliente: "Isabel Santos",
    valor: 850,
    dataVencimento: "2023-09-28",
    status: "Pago",
    descricao: "Compras de supermercado",
  },
  {
    idUsuario: 7,
    nomeCliente: "Ricardo Almeida",
    valor: 600,
    dataVencimento: "2023-10-02",
    status: "Pendente",
    descricao: "Pagamento de conta de energia",
  },
  {
    idUsuario: 8,
    nomeCliente: "Mariana Lima",
    valor: 400,
    dataVencimento: "2023-09-22",
    status: "Pago",
    descricao: "Manutenção de computador",
  },
  {
    idUsuario: 9,
    nomeCliente: "Carlos Souza",
    valor: 1100,
    dataVencimento: "2023-10-08",
    status: "Pendente",
    descricao: "Pagamento de empréstimo",
  },
  {
    idUsuario: 10,
    nomeCliente: "Laura Santos",
    valor: 950,
    dataVencimento: "2023-09-26",
    status: "Pago",
    descricao: "Compras de roupas",
  },
];
